version: '3.8'

# 🌐 Networks
networks:
  externa:
    external: true
  interna:
    external: true

# 💾 Volumes
volumes:
  mysql_data:
    driver: local
  phpmyadmin_data:
    driver: local

services:
  # 🗄️ MySQL Database Server (Centralizado)
  mysql:

    image: mysql:8.0.28
    networks:
      - interna
    environment:
      - MYSQL_ROOT_PASSWORD=BAAE3A32D667F546851BED3777633
      - TZ=America/Sao_Paulo
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [ node.role == manager ]
      # Recursos comentados
      # resources:
      #   limits:
      #     memory: 1G
      #   reservations:
      #     memory: 512M

  # 🔧 phpMyAdmin (Administração centralizada)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    networks:
      - externa
      - interna
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      # Para produção - Login com credenciais obrigatórias
      - PMA_ARBITRARY=1
      - PMA_CONTROLHOST=mysql
      - TZ=America/Sao_Paulo
      - UPLOAD_LIMIT=64M
      - MEMORY_LIMIT=512M
      - MAX_EXECUTION_TIME=300
    volumes:
      - phpmyadmin_data:/sessions
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - mysql
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [ node.role == manager ]
      labels:
        # 🗄️ Labels do Traefik para phpMyAdmin
        traefik.enable: "true"
        traefik.docker.network: "externa"
        
        # Configuração HTTP para redirecionamento HTTPS
        traefik.http.routers.db-phpmyadmin-http.rule: "Host(`dbadmin.itaperunarj.com.br`)"
        traefik.http.routers.db-phpmyadmin-http.entrypoints: "web"
        traefik.http.routers.db-phpmyadmin-http.middlewares: "redirect-to-https"
        
        # Configuração HTTPS principal
        traefik.http.routers.db-phpmyadmin.rule: "Host(`dbadmin.itaperunarj.com.br`)"
        traefik.http.routers.db-phpmyadmin.entrypoints: "websecure"
        traefik.http.routers.db-phpmyadmin.tls: "true"
        traefik.http.routers.db-phpmyadmin.tls.certresolver: "le"
        traefik.http.routers.db-phpmyadmin.service: "db-phpmyadmin"
        
        # Configuração do serviço
        traefik.http.services.db-phpmyadmin.loadbalancer.server.port: "80"
        
        # Middleware para redirecionamento HTTPS
        traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: "https"
        traefik.http.middlewares.redirect-to-https.redirectscheme.permanent: "true"
        
        # Middleware de autenticação básica (opcional - descomente se quiser dupla proteção)
        # traefik.http.routers.db-phpmyadmin.middlewares: "db-auth"
        # traefik.http.middlewares.db-auth.basicauth.users: "admin:$$2y$$10$$..."
      # Recursos comentados
      # resources:
      #   limits:
      #     memory: 256M
      #   reservations:
      #     memory: 128M
